# Generated by Django 3.0.5 on 2020-11-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0002_auto_20201111_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Москва', max_length=16),
            preserve_default=False,
        ),
    ]
