# Generated by Django 3.0.5 on 2020-11-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0004_auto_20201112_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileclass',
            name='current_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_class.Class'),
        ),
        migrations.AlterField(
            model_name='profileclass',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_class.Profile'),
        ),
    ]
