# Generated by Django 3.0.5 on 2020-11-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0007_auto_20201119_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
