# Generated by Django 3.0.5 on 2020-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0008_profile_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_visit',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
