# Generated by Django 3.0.5 on 2020-11-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0010_auto_20201120_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
