# Generated by Django 3.0.5 on 2020-11-20 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0012_auto_20201120_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_class.Class'),
        ),
    ]
