# Generated by Django 3.0.5 on 2020-11-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0013_auto_20201120_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Классы', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='profileclass',
            options={'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задания', 'verbose_name_plural': 'Задания'},
        ),
    ]
