# Generated by Django 3.0.5 on 2020-11-21 08:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0014_auto_20201120_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
