# Generated by Django 3.0.5 on 2020-12-02 16:37

from django.db import migrations, models
import django.db.models.deletion
import my_class.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0015_auto_20201121_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=my_class.models.generate_teacher_filename, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=my_class.models.generate_teacher_filename, verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_class.Task')),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='student_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_class.StudentAnswer'),
        ),
    ]
