# Generated by Django 3.0.5 on 2020-12-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0016_auto_20201202_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='student_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_class.StudentAnswer'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='author',
            field=models.ManyToManyField(to='my_class.Profile'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='teacher_comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
