# Generated by Django 3.0.5 on 2020-12-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0017_auto_20201202_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='comment',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='teacher_comment',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
