# Generated by Django 3.0.5 on 2020-12-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0018_auto_20201202_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='student_answer',
        ),
    ]
