# Generated by Django 3.0.5 on 2020-12-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0019_remove_images_student_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='is_student_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='is_student_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='student_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_class.StudentAnswer'),
        ),
    ]
