# Generated by Django 3.0.5 on 2020-12-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0020_auto_20201203_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'verbose_name': 'Ответы', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='author',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_class.Profile'),
        ),
    ]
