# Generated by Django 3.0.5 on 2020-12-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0021_auto_20201203_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='edit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
