# Generated by Django 3.0.5 on 2020-12-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0022_task_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='comment',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
