# Generated by Django 3.0.5 on 2020-12-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0024_auto_20201219_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_class.Class'),
        ),
    ]
