# Generated by Django 3.0.5 on 2020-12-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0025_studentanswer_current_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
