# Generated by Django 3.1.4 on 2021-01-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0027_studentanswer_edit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
