# Generated by Django 3.1.4 on 2021-03-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0028_auto_20210120_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('AL', 'Алгебра'), ('BI', 'Биология'), ('GM', 'География'), ('GG', 'Геометрия'), ('LG', 'Лингвистика'), ('MA', 'Математика')], max_length=32, null=True),
        ),
    ]
