# Generated by Django 3.1.4 on 2021-03-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0031_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='profile',
            name='news',
            field=models.ManyToManyField(to='my_class.News', verbose_name='Новости'),
        ),
    ]
