# Generated by Django 3.1.4 on 2021-03-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0032_auto_20210313_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='second_title',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
