# Generated by Django 3.1.4 on 2021-03-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_class', '0034_auto_20210313_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='href',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='second_title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
